-- GUARDIAN v9 - BANCO FIXO DE EVENTOS
-- Execute no SQL Editor do seu Supabase.

create table if not exists guardian_events (
    id bigint generated by default as identity primary key,
    event_id uuid not null unique,
    session_id text not null,
    event_type text not null,
    event_time timestamptz not null,
    app_version text,
    computer_name text,
    data jsonb not null,
    created_at timestamptz not null default now()
);

create index if not exists idx_guardian_events_session
on guardian_events (session_id, event_time);

create index if not exists idx_guardian_events_type
on guardian_events (event_type, event_time);

alter table guardian_events enable row level security;

drop policy if exists "guardian_insert_events" on guardian_events;
create policy "guardian_insert_events"
on guardian_events
for insert
to anon
with check (true);

-- O aplicativo não recebe permissão de leitura, alteração ou exclusão.
-- A consulta dos relatórios deve ser feita pelo painel administrativo,
-- pelo SQL Editor ou por uma API protegida.
