-- Execute no SQL Editor do Supabase

create table if not exists approved_game_files (
    id bigint generated by default as identity primary key,
    game text not null,
    platform text not null,
    relative_path text not null,
    sha256 text not null check (length(sha256) = 64),
    size_bytes bigint not null,
    source text not null default 'steam_clean_install',
    active boolean not null default true,
    created_at timestamptz not null default now(),
    unique (game, platform, relative_path, sha256)
);

create index if not exists idx_approved_game_files_lookup
on approved_game_files (game, platform, relative_path, active);

create table if not exists allowed_software (
    id bigint generated by default as identity primary key,
    product_name text not null,
    process_name text,
    publisher text,
    signer_subject text,
    sha256 text,
    notes text,
    active boolean not null default true,
    created_at timestamptz not null default now()
);

create table if not exists blocked_indicators (
    id bigint generated by default as identity primary key,
    indicator_type text not null,
    indicator_value text not null,
    severity text not null check (severity in ('review', 'confirmed_cheat')),
    family_name text,
    source text,
    notes text,
    active boolean not null default true,
    created_at timestamptz not null default now(),
    unique (indicator_type, indicator_value)
);

-- Exemplos de programas comuns permitidos.
-- O ideal é complementar com assinatura digital, fabricante e hashes quando necessário.
insert into allowed_software (product_name, process_name, publisher, notes)
values
('Steam', 'steam.exe', 'Valve Corp.', 'Cliente oficial da Steam'),
('Discord', 'discord.exe', 'Discord Inc.', 'Comunicação permitida'),
('Spotify', 'spotify.exe', 'Spotify AB', 'Reprodução de música permitida'),
('OBS Studio', 'obs64.exe', 'OBS Project', 'Gravação e transmissão permitidas')
on conflict do nothing;
