; Script generated by the Inno Setup Script Wizard.
; Non-commercial use only

#define MyAppName "Guardian"
#define MyAppVersion "1.0"
#define MyAppPublisher "Raaaif, Inc."
#define MyAppURL "https://www.raaaif.com/"
#define MyAppExeName "Guardian.exe"
#define MyAppIcon "C:\Users\raifs\OneDrive\Área de Trabalho\Guardian\assets\Guardian.ico"

[Setup]
AppId={{53D2E6FC-0943-4AD0-AD72-F577419D1DC9}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}

DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}

UninstallDisplayIcon={app}\{#MyAppExeName}
SetupIconFile={#MyAppIcon}

ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible

DisableProgramGroupPage=yes
PrivilegesRequired=admin

OutputDir=C:\Users\raifs\OneDrive\Área de Trabalho\Guardian\installer
OutputBaseFilename=GuardianSetup

Compression=lzma2
SolidCompression=yes
WizardStyle=modern dark polar

[Languages]
Name: "portuguese"; MessagesFile: "compiler:Languages\Portuguese.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\raifs\OneDrive\Área de Trabalho\Guardian\bin\Release\net8.0-windows\win-x64\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "Abrir {#MyAppName}"; Flags: nowait postinstall skipifsilent